//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Accounts
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public string LoginSkype { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public System.DateTime DateRegister { get; set; }
    }
}
