//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameters
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public float Price { get; set; }
        public int AmountDeals { get; set; }
        public float VolumeDeals { get; set; }
        public float Volatility { get; set; }
        public int VolumeOpenInterest { get; set; }
        public Nullable<System.DateTime> DateRegiser { get; set; }
    }
}
